services:
  app:
    image: node:22-alpine
    container_name: etl_app
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsup.config.ts:/app/tsup.config.ts
      - ./products.csv:/app/products.csv
    command: sh -c "npm install && npm run build && npm run start"
    environment:
      - DATABASE_URL=postgres://cortelucas:luc@sC06@db:5432/etl_db
      - SMB_SHARE=\\\\smb\\share
      - SMB_DOMAIN=WORKGROUP
      - SMB_USER=smvserver
      - SMB_PASS=Server123
    depends_on:
      db:
        condition: service_healthy
      smb:
        condition: service_started

  db:
    image: bitnami/postgresql:latest
    container_name: etl_db
    restart: always
    environment:
      - POSTGRESQL_USERNAME=cortelucas
      - POSTGRESQL_PASSWORD=luc@sC06
      - POSTGRESQL_DATABASE=etl_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/bitnami/postgresql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "cortelucas", "-d", "etl_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  smb:
    image: dperson/samba
    container_name: etl_smb
    restart: always
    command: -s "share;/share;yes;no;yes"
    volumes:
      - ./smbshare:/share
    ports:
      - "139:139"
      - "445:445"

volumes:
  pgdata:
